version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"

  flask_app:
    build: .
    container_name: flask-app
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5001:5000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  celery_worker:
    build: .
    container_name: celery-worker
    command: celery -A celery_config.app worker --loglevel=info
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    container_name: celery-beat
    command: celery -A celery_config.app beat --loglevel=info
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

volumes:
  mysql_data:
